# vi: ft=make
.PHONY: proto test

proto:
	go get github.com/golang/protobuf/protoc-gen-go
	protoc -I . {{ .Name }}.proto --lile-server_out=. --go_out=plugins=grpc,paths=source_relative:.  --swagger_out=logtostderr=true:. --grpc-gateway_out=logtostderr=true:.

test: proto
	go test -p 1 -v ./...

init: proto
	go mod tidy
	go mod vendor
