# vi: ft=make
.PHONY: proto test

proto:
	protoc --openapiv2_out . --openapiv2_opt logtostderr=true \
               --openapiv2_opt allow_merge=true \
        	   -I . \
        	   --lile-server_out=. \
        	   --go_out=paths=source_relative:. \
        	   --go-grpc_out=paths=source_relative:. \
        	   --grpc-gateway_out paths=source_relative:. \
        	   --grpc-gateway_opt logtostderr=true \
        	   --grpc-gateway_opt generate_unbound_methods=true \
        	   --validate_out="lang=go,paths=source_relative:." \
        	   {{ .Name }}.proto
test: proto
	go test -p 1 -v ./...

init: proto
	go mod tidy
	go mod vendor
